version: '3.4'

services:
  request_response:
    container_name: "request_response"
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
     - $API_PORT:80
    environment: 
     - ASPNETCORE_ENVIRONMENT=Production